//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1174.0 using the following command:
// xscgen --namespaceHierarchy -o .\src\model .\schemas\*.xsd
namespace Mets
{


    /// <summary>
    /// Represents the shape types for an area in the METS schema.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AreaTypeShape", Namespace = "http://www.loc.gov/METS/", AnonymousType = true)]
    public enum AreaTypeShape
    {

        [System.Xml.Serialization.XmlEnumAttribute("RECT")]
        RECT,

        [System.Xml.Serialization.XmlEnumAttribute("CIRCLE")]
        CIRCLE,

        [System.Xml.Serialization.XmlEnumAttribute("POLY")]
        POLY,
    }
}
